### ISSUE TITLE
It doesn't work with 3.5e SRD system.

### ISSUE THREAD

**Issue by ilore** [SebaSOFT/walls-have-ears#21] opened 2022-03-02 09:51 UTC
This module doesn't work with 3.5e SRD system. It does nothing when you activate it.

**Comment by NdranC** [comment] 2022-03-07 23:44
I just wanted to add to this, since it seems I have a similar problem with 5e (although I doubt it has anything to do with the game system). The module is not working at all. 

I disabled all modules except for Module Management, Force Settings and this module.

I can confirm that token vision is enabled on the scene.

My token is in an enclosed room with rain outside 
![image](https://user-images.githubusercontent.com/27837113/157137089-db238b8f-cdc1-4fe9-b78b-a3dd70a50439.png)
The rain origin is at my mouse location and it's set to NOT ease or NOT be blocked by walls.

**Comment by ilore** [comment] 2022-03-07 23:52
> Please follow this check list:
> 
> * Disable any other modules (specially better roofs and levels)
> * Make sure token vision is enabled on the scene
> * Make sure the sound actually goes through walls
> 
> The code in the module does nothing on checking the system so is system agnostic.

I have tried to disable all modules and the sound goes through walls. It still doesn't work.

**Comment by SebaSOFT** [comment] 2022-03-08 04:38
> I just wanted to add to this, since it seems I have a similar problem with 5e (although I doubt it has anything to do with the game system). The module is not working at all.
> 
> I disabled all modules except for Module Management, Force Settings and this module.
> 
> I can confirm that token vision is enabled on the scene.
> 
> My token is in an enclosed room with rain outside ![image](https://user-images.githubusercontent.com/27837113/157137089-db238b8f-cdc1-4fe9-b78b-a3dd70a50439.png) The rain origin is at the compass location and it's set to NOT ease or NOT be blocked by walls.

Can you move to the sound editing mode and show me the sound poligon for that screen?

**Comment by NdranC** [comment] 2022-03-08 05:04
![image](https://user-images.githubusercontent.com/27837113/157169545-9a371620-94b6-4f61-b8dd-ef968face9a7.png)

The smaller inside sounds are the braziers (I tried removing them to see if they were interfering but nothing changed.

I was testing your mod with the idea of replicating outside rain vs inside muted rain all in the same scene based on token position.

Let me know if I can help you in any other way.

**Comment by SebaSOFT** [comment] 2022-03-08 13:17
> 
> The smaller inside sounds are the braziers (I tried removing them to see if they were interfering but nothing changed.
> 
> I was testing your mod with the idea of replicating outside rain vs inside muted rain all in the same scene based on token position.
> 
> Let me know if I can help you in any other way.

It looks like is something that should work. I will try to recreate the scene since there is no good way to export this now so I can debug. Maybe the sound doesnt have a lot of low (bass) components so the low pass filter doesnt affect it too much. 

As soon as I recreate I will send you a video of it

**Comment by NdranC** [comment] 2022-03-08 13:55
The reason why I was so sure something must not be working, is because I teleported the token all around the castle through multiple layers of walls and the sound (to my ears) never changed. I'm keeping the module installed and maybe setup a new scene with different music to see if I can spot it.

If I understand your table correctly, 3 layers of solid walls should be maximum muffle. It should be pretty noticeable.

**Comment by SebaSOFT** [comment] 2022-03-08 19:02
> 
> If I understand your table correctly, 3 layers of solid walls should be maximum muffle. It should be pretty noticeable.

you are correct

**Comment by NdranC** [comment] 2022-03-10 09:04
Just a minor update. I went ahead and sat down and tested this mod on a new scene, with a full song through several layers of walls around my character and the source of the sound and nothing changed. Sounds exactly the same.

I don't know if there is anything else I could do to provide more info. I tried looking in the console but I'm unsure as to what I should be looking into.

**Comment by BlauKreuz** [comment] 2022-03-10 15:41
I've been following this discussion and just an observation that in my Desktop Foundry v9 **muffling works ok regardless of this "Constrained By Walls" setting**. If it is on, the walls set to block sound block it, if is is off they do not block the sound, but muffling still works ok in both cases behind those walls that are set to Sound Restriction: "None"

Constrained By Walls affects only the walls set to Sound Restriction: "Normal"

![image](https://user-images.githubusercontent.com/96351604/157696762-3d139b8c-4edf-46e3-80d2-8ad52dc287e2.png)
![image](https://user-images.githubusercontent.com/96351604/157697224-e5ebf5ba-8977-4d9a-8156-af5fcb345c27.png)

**Comment by SebaSOFT** [comment] 2022-03-10 21:56
Let's start with this. I will develop a debug toggle on the settings (default: false) so you can enable this and the console will start showing all sounds and muffling levels, also why is resolving that muffling level. I-m affraid that if the sound is blocked for some reason, the module doesnt have access to such sound source (ie is behind a wall and constrained), but if appears in the sound list, it should estimate muffling levels.

**Comment by SebaSOFT** [comment] 2022-04-20 14:00
@BlauKreuz now you can see the debug console with all the data to troubleshoot your scene. Please update to 1.0.1 and the latest FoundryVTT core

**Comment by NdranC** [comment] 2022-04-21 00:34
> @BlauKreuz now you can see the debug console with all the data to troubleshoot your scene. Please update to 1.0.1 and the latest FoundryVTT core

Test setup
![image](https://user-images.githubusercontent.com/27837113/164346137-c50cc1ca-7eaf-4453-9c18-e9be43355221.png)

Console Debug
![image](https://user-images.githubusercontent.com/27837113/164345970-2778f1b4-e76b-402e-9dd8-774677aa6b85.png)

By chance I'm also noticing an error when I have a scene with no walls but with sound sources
![image](https://user-images.githubusercontent.com/27837113/164346640-5f27fbaf-fd0a-4656-8824-6b6173bfcf42.png)

If you need more formal testing, let me know. I was randomly running around a map I have and I was able to tell once the sounds getting muffled. I was not able to get it working again so I'm not sure why it randomly worked under that circumstance.

**Comment by SebaSOFT** [comment] 2022-04-21 02:15
Thanks for the headsup on the empty maps, will test and fix that. For your problem, the issue could be:
- The sound is not constrained by walls (this is new setting) preventing any vision calculation but can be heard
- Another mod interfiering with vision/polygon calculation
- An error with sound filters for your sound drivers
- An error on FVTT itself

For many of those I do think I should be getting more error reports (2.8k installations aprox.)

Check version 1.0.2, this should simplify things more, now "Contrained by Walls" is a requirement

**Comment by NdranC** [comment] 2022-04-21 03:35
Ok... I'm a little confused. I'm not sure if this was a massive user error on my side or things changed along the way. I went to re-read your usage instructions and they seem to be different to what I remember.

I can get the mod to work if:

1. The sound is constrained by walls
2. The wall is marked as "Limited" for sound.
3. There is ONLY 1 wall in between me and the sound. If I add more walls with "Limited" for sound they block the sound completely.

But I'm also re-watching the video you have with the Test Suit and I can see you have multiple levels of muffling with 3 walls in a row. How can I get the sound to be muffled even more by more walls?

**Closed** 2022-04-21 18:28 UTC
Labels: question
